services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
    networks:
      - iotnet

  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    networks:
      - iotnet
    # restart: unless-stopped

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    networks:
      - iotnet

networks:
  iotnet:
    driver: bridge